- title: PR Automation ( Jenkins-Bitbucket Integration)
  desc: Jenkins-Bitbucket Integration to merge the Code to master -once the developer Pull-request the code, automatic trigger build will happen in Jenkins and once the build status succeed sends notification to Bitbucket to merge the code to master

- title: Twilio Integration for critical alarms
  desc: Voice call support to teams, once alarm imitated lambda function will send the alarm to S3 where AWS Polly convert it to speech and twilo makes a call to the respective support member and sends the data to S3 once the call answered

- title: Terraform Blast Radius
  desc: Open policy agent use cases for terraform compliance (blast radius check)

- title: Terraform Compliance
  desc: Conftest - Tests against structured configuration data using the Open Policy Agent Rego querylanguage

- title: Zero DownTime Deployments
  desc: Blue/green & Canary deployments

- title: Apache Kafka Monitoring
  desc: AWS EKS deployed Apacje kafka monitoring via prometheus and grafana and alert management via cloudwatch prometheus agent
