- title: Jenkins-Bitbucket Integration
  desc: Jenkins-Bitbucket Integration to merge the Code to master -once the developer Pull-request the code, automatic trigger build will happen in Jenkins and once the build status succeed sends notification to Bitbucket to merge the code to master
  icon: assets/images/services-icon-brush.png

- title: Twilio Integration
  desc: Voice call support to teams, once alarm imitated lambda function will send the alarm to S3 where AWS Polly convert it to speech and twilo makes a call to the respective support member and sends the data to S3 once the call answered.
  icon: assets/images/services-icon-java.png
  
- title: Terraform Compliance
  desc: Open policy agent use cases for terraform compliance (blast radius check)
  icon: assets/images/services-icon-coding.png

- title: Terraform unit testing
  desc: - conftest - Tests against structured configuration data using the Open Policy Agent Rego query language
  icon: assets/images/services-icon-layer.png